# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Aditya Rahmanda
author: Aditya Rahmanda
email: arahmanda21@gmail.com
description: >- 
  Pengembang Game dan Budak Kucing
domain: adityarahmanda.github.io # the subpath of your site, e.g. /blog
url: https://adityarahmanda.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /adityarahmanda.github.io
lang: id
google_analytics: G-J57JE933K5
github_username:  adityarahmanda
translations:
  id:
    home_path: /
    navigations:
      - label: Artikel
        path: artikel
      - label: Kerjaan
        path: kerjaan
    resume: "Lihat Resume"
    works: "Kerjaan"
    articles: "Artikel"
    read_more: "Baca Selengkapnya"
    labels: "Label"
    tools: "Perkakas"
    made_with_love: "Dibuat dengan Sepenuh Hati"
    applause: "Tinggalkan tepuk tangan jika artikel ini bermanfaat"
    search: "Cari"
  en:
    home_path: /en
    navigations:
      - label: Articles
        path: /en/articles
      - label: Works
        path: /en/works
    resume: "See Resume"
    works: "Works"
    articles: "Articles"
    read_more: "Read More"
    labels: "Labels"
    tools: "Tools"
    made_with_love: "Made With Love"
    applause: "Leave applause if you think this article is useful"
    search: "Search"
social_links:
    - { platform: github,         user_url: "https://github.com/adityarahmanda" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/adityarahmanda" }
    - { platform: behance,        user_url: "https://behance.net/adityarahmanda" }
    - { platform: instagram,      user_url: "https://www.instagram.com/arahmanda21" }

# Build settings
theme: minima
collections:
  id:
    output: true
    permalink: /:collection/:slug
  en:
    output: true
    permalink: /:collection/:slug
plugins:
  - jekyll-seo-tag
  - jekyll-feed
permalink: /:categories/:title
excerpt_separator: <!--excerpt-->
language_default: id
collections_dir: content
defaults:
- scope:
    path: '_id/posts'
  values:
    permalink: 'kerjaan/:slug'
    language: id
- scope:
    path: '_id/articles'
  values:
    permalink: 'artikel/:name'
    language: id
- scope:
    path: '_en/posts'
  values:
    permalink: 'en/works/:slug'
    language: en
- scope:
    path: '_en/articles'
  values:
    permalink: 'en/articles/:name'
    language: en
feed:
  collections:
    - id
    - en


# Include to processing
include:
  - .well-known

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
